sudo: false
language: php
php:
 - '7.2'

env:
 - KOHARNESS_ALL_MODULES=1
 - KOHARNESS_ALL_MODULES=0

# Only build the main develop/master branches - feature branches will be covered by PRs
branches:
  only:
    - /^[0-9\.]+\.x$/

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - COMPOSER_ROOT_VERSION=3.3.x-dev composer install --prefer-dist --no-interaction
  - vendor/bin/koharness

script:
  - cd /tmp/koharness && ./vendor/bin/phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  email: false
